"""Format string used for saving coefficients generated by the continuous wavelet
transform of a fast5 signal. The format should be:
"cwt_<signal_name>_<wavelet>_<scale>_<absolute>"
"""
CWT_SAVE_STRING_FORMAT = "cwt_{}_{}_{}_{}.p"

"""Format string used for saving coefficients generated by the discrete wavelet
transform of a fast5 signal. The format should be:
"dwt_<signal_name>_<wavelet>_<level>"
"""
DWT_SAVE_STRING_FORMAT = "dwt_{}_{}_{}.p"

"""Format string used for saving coefficients generated by the continuous wavelet transform of the discrete wavelet
transform of a fast5 signal. The format should be:
"dwt_cwt_<signal_name>_<discrete_wavelet>_<level>_<continuous_wavelet>_<scale>_<absolute>"
"""
DWT_CWT_SAVE_STRING_FORMAT = "dwt_cwt_{}_{}_{}_{}_{}_{}.p"

PREPROCESS_TOMBO = "tombo"

PREPROCESS_NONE = "none"

TRANSFORMS_CWT = "cwt"

TRANSFORMS_DWT_CWT = "dwt-cwt"

FINGERPRINTING_CONSTELLATION = "constellation"

FINGERPRINTING_MINHASH = "minhash"

"""Format string for saving the wavelet fingerprinting pipeline output. The format should be:
"pipeline_<file>_<preprocess_descriptor>_<transform_descriptor>_<fingerprinting_descriptor>"
"""
PIPELINE_RESULT = "pipeline_{}_{}_{}_{}.p"

SIMILARITY_CONSTELLATION = "constellation"

SIMILARITY_LSH = "lsh"
